sudo: true

language: cpp

compiler: gcc

env:
  # - TEST="valgrind" # commented out until you finish the simulator code
  - TEST="unit" TYPE="[network]"
  - TEST="unit" TYPE="[backprop]"
  - TEST="unit" TYPE="[simulator]" # commented out while it doesnt work

before_install:
  # Valgrind
  - if [[ "$TEST" == "valgrind" ]]; then sudo apt-get install valgrind; fi

  # SFML
  - wget http://sfml-dev.org/download/sfml/2.1/SFML-2.1-linux-gcc-64bits.tar.bz2 -O /tmp/sfml.tar.bz2
  - tar -xjvf /tmp/sfml.tar.bz2
  - sudo cp -r SFML-2.1/* /usr/
  - sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1

  # g++4.8.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -qq libstdc++6-4.7-dev
  - export CXXFLAGS="-std=c++0x"
  - export CXX="g++-4.8"

script:
  # Build
  - cd ~/build/FidoProject/Fido
  - make && sudo make install
  # Run Unit Tests
  - if [[ "$TEST" == "unit" ]]; then sudo ./runtests.sh $TYPE; fi
  # Run Valgrind on unit tests
  - if [[ "$TEST" == "valgrind" ]]; then cd tests/; make; mkdir -p temp; valgrind --leak-check=full --error-exitcode=1 ./tests.o; fi
